[package]
name = "rusty_skelform_macroquad"
version = "0.2.0"
edition = "2021"
description = "SkelForm Macroquad runtime"
license = "MIT"

[dependencies]
macroquad = "0.4.14"
quad-gl = "0.2.13"
rusty_skelform = "0.2.0"
serde_json = "1.0.140"
zip = "2.6.1"
